services:
  - type: web
    name: lexsy-backend
    runtime: python
    region: oregon
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_PARSER_ASSISTANT_ID
        sync: false
      - key: OPENAI_FILLER_ASSISTANT_ID
        sync: false
